# Dependencies
markdown:         redcarpet
highlighter:      pygments.rb

# Permalinks
permalink:        pretty

# Setup
title:            LDI Dev Edition
tagline:          'A person'
description:      'Nothing to report'
url:              http://ruiorey.github.io
baseurl:          /

author:
  name:           'Rui Orey'
  url:            http://twitter.com/RuiOrey

plugins: 
  - jekyll-paginate 
  - jekyll-gist
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           http://github.com/ruiorey
